import Link from 'next/link';
import {createClient} from '@/lib/supabase/server';
import {Icon} from '@/components/icon';
import {ReportList,ReportListItem} from '@/components/report-list';
import {ReportFilters} from '@/components/report-filters';

const PAGE_SIZE=20;
type Params={q?:string;asal?:string;status?:string;kecamatan?:string;jenis?:string;page?:string};

export default async function Arsip({searchParams}:{searchParams:Params}){
  const s=createClient(),q=(searchParams.q||'').trim().slice(0,100),asal=['Manual','Import'].includes(searchParams.asal||'')?searchParams.asal!:'',status=(searchParams.status||'').trim(),kecamatan=(searchParams.kecamatan||'').trim(),jenis=(searchParams.jenis||'').trim(),requestedPage=Math.max(1,Number.parseInt(searchParams.page||'1',10)||1);
  let manual=s.from('laporan_kerusakan').select('id,nomor_laporan,created_at,waktu_laporan,nama_pelapor,nama_petugas_input,nama_jalan,kecamatan,kelurahan,jenis_perlengkapan,tingkat_kerusakan,status,deskripsi').order('waktu_laporan',{ascending:false}).limit(1000);
  let imported=s.from('imported_laporan_kerusakan').select('id,nomor_import,waktu_laporan,nama_pelapor,nama_petugas_input,nama_jalan,kecamatan,kelurahan,jenis_perlengkapan,tingkat_kerusakan,status,deskripsi').order('waktu_laporan',{ascending:false}).limit(1000);
  if(q){const safe=q.replace(/[,%()]/g,' ');manual=manual.or(`nomor_laporan.ilike.%${safe}%,nama_pelapor.ilike.%${safe}%,nama_jalan.ilike.%${safe}%,kelurahan.ilike.%${safe}%`);imported=imported.or(`nomor_import.ilike.%${safe}%,nama_pelapor.ilike.%${safe}%,nama_jalan.ilike.%${safe}%,kelurahan.ilike.%${safe}%`)}
  if(status){manual=manual.eq('status',status);imported=imported.eq('status',status)}
  if(kecamatan){manual=manual.eq('kecamatan',kecamatan);imported=imported.eq('kecamatan',kecamatan)}
  if(jenis){manual=manual.eq('jenis_perlengkapan',jenis);imported=imported.eq('jenis_perlengkapan',jenis)}
  const [{data:m},{data:i},{data:districts},{data:types}]=await Promise.all([manual,imported,s.from('ref_kecamatan').select('nama').order('nama'),s.from('ref_jenis_perlengkapan').select('nama').eq('aktif',true).order('nama')]);
  const all:ReportListItem[]=[
    ...((asal!=='Import'?m:[])||[]).map(r=>({id:r.id,nomor:r.nomor_laporan,waktu:r.waktu_laporan||r.created_at,pelapor:r.nama_pelapor,lokasi:r.nama_jalan,wilayah:`${r.kelurahan}, ${r.kecamatan}`,jenis:r.jenis_perlengkapan,tingkat:r.tingkat_kerusakan,status:r.status,deskripsi:r.deskripsi,petugas:r.nama_petugas_input,asal:'Manual' as const,href:'/laporan/'+r.id})),
    ...((asal!=='Manual'?i:[])||[]).map(r=>({id:r.id,nomor:r.nomor_import,waktu:r.waktu_laporan,pelapor:r.nama_pelapor,lokasi:r.nama_jalan,wilayah:`${r.kelurahan}, ${r.kecamatan}`,jenis:r.jenis_perlengkapan,tingkat:r.tingkat_kerusakan,status:r.status,deskripsi:r.deskripsi,petugas:r.nama_petugas_input,asal:'Import' as const,href:'/laporan/import/arsip/'+r.id}))
  ].sort((a,b)=>new Date(b.waktu).getTime()-new Date(a.waktu).getTime());
  const totalPages=Math.max(1,Math.ceil(all.length/PAGE_SIZE)),page=Math.min(requestedPage,totalPages),from=(page-1)*PAGE_SIZE,items=all.slice(from,from+PAGE_SIZE),hasFilter=Boolean(q||asal||status||kecamatan||jenis);
  const pageHref=(target:number)=>{const p=new URLSearchParams();if(q)p.set('q',q);if(asal)p.set('asal',asal);if(status)p.set('status',status);if(kecamatan)p.set('kecamatan',kecamatan);if(jenis)p.set('jenis',jenis);p.set('page',String(target));return '/laporan?'+p};
  const filterHref=(source:string)=>{const p=new URLSearchParams();if(q)p.set('q',q);if(source)p.set('asal',source);if(status)p.set('status',status);if(kecamatan)p.set('kecamatan',kecamatan);if(jenis)p.set('jenis',jenis);return '/laporan?'+p};
  const chipHref=(remove:string)=>{const p=new URLSearchParams();if(q&&remove!=='q')p.set('q',q);if(asal&&remove!=='asal')p.set('asal',asal);if(status&&remove!=='status')p.set('status',status);if(kecamatan&&remove!=='kecamatan')p.set('kecamatan',kecamatan);if(jenis&&remove!=='jenis')p.set('jenis',jenis);return '/laporan?'+p};
  return <section className="space-y-5">
    <header className="rounded-2xl bg-gradient-to-r from-indigo-950 via-indigo-800 to-blue-700 p-6 text-white shadow-lg md:p-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-bold tracking-[.16em] text-cyan-200">ARSIP TERPADU</p><h1 className="mt-2 text-2xl font-bold">Semua Laporan</h1><p className="mt-2 max-w-2xl text-sm text-indigo-100">Laporan manual dan data import dikelola dari satu halaman. Gunakan filter untuk mempersempit data.</p></div><div className="flex gap-2"><Link href="/laporan/rekap" className="inline-flex items-center gap-2 rounded-xl bg-white/10 px-4 py-2.5 text-sm font-semibold ring-1 ring-white/20"><Icon name="print" className="h-4 w-4"/>Rekap & Export</Link><Link href="/laporan/tambah" className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-indigo-700"><Icon name="plus" className="h-4 w-4"/>Tambah</Link></div></div></header>
    <div className="flex gap-2 overflow-x-auto rounded-xl border bg-white p-1.5 shadow-sm">{[['','Semua'],['Manual','Manual'],['Import','Import']].map(([value,label])=><Link key={label} href={filterHref(value)} className={'whitespace-nowrap rounded-lg px-4 py-2 text-sm font-semibold transition '+(asal===value?'bg-indigo-700 text-white shadow-sm':'text-slate-500 hover:bg-slate-50 hover:text-indigo-700')}>{label}</Link>)}</div>
    <ReportFilters current={{q,asal,status,kecamatan,jenis}} districts={(districts||[]).map(x=>x.nama)} types={(types||[]).map(x=>x.nama)}/>
    {hasFilter&&<div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold text-slate-400">Filter aktif:</span>{q&&<Chip label={`Cari: ${q}`} href={chipHref('q')}/>} {asal&&<Chip label={asal} href={chipHref('asal')}/>} {status&&<Chip label={status} href={chipHref('status')}/>} {kecamatan&&<Chip label={kecamatan} href={chipHref('kecamatan')}/>} {jenis&&<Chip label={jenis} href={chipHref('jenis')}/>}<Link href="/laporan" className="px-2 py-1 text-xs font-semibold text-rose-600">Reset semua</Link></div>}
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-4"><div><h2 className="font-semibold">Daftar Laporan</h2><p className="text-xs text-slate-500">{all.length} laporan ditemukan · terbaru terlebih dahulu</p></div>{asal==='Import'&&<Link href="/laporan/import" className="text-xs font-semibold text-cyan-700">+ Import data baru</Link>}</div><ReportList items={items} empty="Tidak ada laporan yang sesuai filter."/><footer className="flex flex-wrap items-center justify-between gap-3 border-t px-4 py-3"><p className="text-sm text-slate-500">Menampilkan <b>{all.length?from+1:0}–{Math.min(from+items.length,all.length)}</b> dari <b>{all.length}</b></p><div className="flex items-center gap-2">{page>1?<Link href={pageHref(page-1)} className="rounded-lg border px-3 py-2 text-sm font-semibold">← Sebelumnya</Link>:<span className="rounded-lg border border-slate-100 px-3 py-2 text-sm text-slate-300">← Sebelumnya</span>}<span className="text-sm text-slate-500">{page} / {totalPages}</span>{page<totalPages?<Link href={pageHref(page+1)} className="rounded-lg border px-3 py-2 text-sm font-semibold">Berikutnya →</Link>:<span className="rounded-lg border border-slate-100 px-3 py-2 text-sm text-slate-300">Berikutnya →</span>}</div></footer></div>
  </section>
}

function Chip({label,href}:{label:string;href:string}){return <Link href={href} title="Hapus filter" className="rounded-full border border-indigo-100 bg-indigo-50 px-3 py-1.5 text-xs font-semibold text-indigo-700 transition hover:bg-indigo-100">{label} ×</Link>}
