'use client';import {useEffect,useState} from 'react';
type Folder={id:string;name:string;webViewLink?:string};type State={connected:boolean;account?:{email:string;name:string;photo?:string};selected?:{folder_id:string;folder_name:string;folder_url?:string};folders?:Folder[];error?:string};
export default function DriveSettings(){const [data,setData]=useState<State|null>(null),[busy,setBusy]=useState(false),[name,setName]=useState(''),[message,setMessage]=useState('');async function load(){const r=await fetch('/api/google/settings',{cache:'no-store'});setData(await r.json())}useEffect(()=>{load()},[]);async function post(body:object){setBusy(true);setMessage('');const r=await fetch('/api/google/settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),j=await r.json();setMessage(j.error||'Pengaturan folder berhasil disimpan.');if(r.ok){setName('');await load()}setBusy(false)}async function disconnect(){if(!confirm('Putuskan akun Google Drive yang terhubung?'))return;setBusy(true);await fetch('/api/google/settings',{method:'DELETE'});window.location.reload()}
  if(!data)return <div className="grid min-h-64 place-items-center text-sm text-slate-500">Memuat pengaturan Google Drive…</div>;
  return <section className="mx-auto max-w-5xl space-y-6"><header className="rounded-2xl bg-gradient-to-r from-indigo-900 via-blue-800 to-cyan-700 p-6 text-white"><p className="text-xs font-bold tracking-[.16em] text-cyan-200">PENGATURAN ADMIN</p><h1 className="mt-2 text-2xl font-bold">Penyimpanan Google Drive</h1><p className="mt-2 text-sm text-blue-100">Tentukan akun pemilik dan folder induk untuk seluruh arsip serta hasil export.</p></header>
    {!data.connected?<div className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><h2 className="font-bold text-amber-950">Google Drive belum terhubung</h2><p className="mt-2 text-sm text-amber-800">Hubungkan akun Google yang akan menjadi pemilik file hasil export.</p><a href="/api/google/connect?returnTo=/pengaturan/google-drive" className="mt-4 inline-block rounded-xl bg-blue-700 px-5 py-3 text-sm font-semibold text-white">Hubungkan Google Drive</a></div>:<>
      <div className="grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Akun penyimpanan aktif</p><div className="mt-4 flex items-center gap-4">{data.account?.photo?<img src={data.account.photo} alt="" className="h-12 w-12 rounded-full"/>:<div className="grid h-12 w-12 place-items-center rounded-full bg-blue-100 font-bold text-blue-700">G</div>}<div><h2 className="font-bold text-slate-900">{data.account?.name||'Akun Google'}</h2><p className="text-sm text-slate-500">{data.account?.email}</p></div></div><div className="mt-5 flex gap-2"><a href="/api/google/connect?returnTo=/pengaturan/google-drive" className="rounded-lg bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white">Ganti akun</a><button onClick={disconnect} disabled={busy} className="rounded-lg border border-rose-200 px-4 py-2.5 text-sm font-semibold text-rose-700">Putuskan</button></div></article>
        <article className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Folder tujuan aktif</p><h2 className="mt-3 text-xl font-bold text-emerald-950">{data.selected?.folder_name||'Drive Saya'}</h2><p className="mt-2 text-sm text-emerald-800">Folder harian hasil export akan dibuat di dalam folder ini.</p>{data.selected?.folder_url&&<a href={data.selected.folder_url} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-semibold text-emerald-800 underline">Buka folder di Drive ↗</a>}</article></div>
      <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold">Pilih folder yang sudah ada</h2><p className="mt-1 text-sm text-slate-500">Daftar folder milik akun {data.account?.email}.</p><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{data.folders?.map(f=><button key={f.id} disabled={busy} onClick={()=>post({action:'select',folderId:f.id})} className={'flex items-center justify-between rounded-xl border p-3 text-left text-sm '+(data.selected?.folder_id===f.id?'border-blue-500 bg-blue-50 font-semibold text-blue-800':'border-slate-200 hover:border-blue-300')}><span className="truncate">📁 {f.name}</span>{data.selected?.folder_id===f.id&&<span>✓</span>}</button>)}</div></div>
      <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold">Buat folder baru</h2><p className="mt-1 text-sm text-slate-500">Folder dibuat di dalam folder tujuan yang saat ini aktif dan langsung dipilih.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Contoh: Arsip Dishub Kota Madiun" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-blue-500"/><button onClick={()=>post({action:'create',name,parentId:data.selected?.folder_id||'root'})} disabled={busy||!name.trim()} className="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy?'Memproses…':'Buat & Gunakan Folder'}</button></div></div>
    </>}{(message||data.error)&&<p className="rounded-xl bg-slate-900 p-4 text-sm text-white">{message||data.error}</p>}</section>}
