import { NextResponse } from 'next/server';
import { createHash } from 'crypto';
import { google } from 'googleapis';
import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { getGoogleOAuth } from '@/lib/google-oauth';
import {getDriveParent} from '@/lib/google-drive-settings';

type Row=Record<string,string>;
const value=(row:Row,key:string)=>row[key]?.trim()||'';
const source=(v:string)=>v==='Instansi Lain'?'Lainnya':['Masyarakat','Petugas Lapangan','Kepolisian','Lainnya'].includes(v)?v:'Lainnya';
const level=(v:string)=>['Ringan','Sedang','Berat','Darurat'].find(x=>v.toLowerCase().startsWith(x.toLowerCase()))||'';
const status=(v:string)=>v==='Dalam Proses'?'Dalam Proses':v==='Selesai'?'Selesai':'Belum Ditangani';
function date(value:string){if(!value)return null;const clean=value.trim().replace(/\/\s*/, ' ');const ymd=clean.match(/^(\d{4})-(\d{1,2})-(\d{1,2})\s+(\d{1,2}:\d{2}(?::\d{2})?)$/);if(ymd){const parsed=new Date(`${ymd[1]}-${ymd[2].padStart(2,'0')}-${ymd[3].padStart(2,'0')}T${ymd[4]}+07:00`);return Number.isNaN(parsed.getTime())?null:parsed.toISOString()}const mixed=clean.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})\s+(\d{1,2}:\d{2}(?::\d{2})?)$/);if(mixed){const first=Number(mixed[1]),second=Number(mixed[2]),month=second>12?first:second,day=second>12?second:first,parsed=new Date(`${mixed[3]}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}T${mixed[4]}+07:00`);return Number.isNaN(parsed.getTime())?null:parsed.toISOString()}const d=new Date(clean.includes('T')?clean:clean.replace(' ','T')+'+07:00');return Number.isNaN(d.getTime())?null:d.toISOString();}
function links(value:string){const markdown=[...value.matchAll(/\[(https?:\/\/[^\]]+)\]/g)].map(x=>x[1]);const plain=value.match(/https?:\/\/[^\s\])]+/g)||[];return [...new Set((markdown.length?markdown:plain).map(x=>x.trim()))];}
function spreadsheetId(input:string){return input.match(/\/spreadsheets\/d\/([\w-]+)/)?.[1]||(/^[\w-]{20,}$/.test(input)?input:'');}

export async function POST(req:Request){try{
  const body=await req.json() as {spreadsheetUrl?:string;sheetName?:string};const id=spreadsheetId(body.spreadsheetUrl||'');if(!id)return NextResponse.json({error:'URL atau ID Google Sheet tidak valid.'},{status:400});
  const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Sesi login tidak valid.'},{status:401});const admin=createAdminClient();
  const {data:token,error:tokenError}=await admin.from('google_oauth_tokens').select('refresh_token').eq('user_id',user.id).maybeSingle();if(tokenError)throw tokenError;if(!token)return NextResponse.json({error:'Google Drive belum terhubung.',connectUrl:'/api/google/connect'},{status:409});
  const auth=getGoogleOAuth();auth.setCredentials({refresh_token:token.refresh_token});const sheets=google.sheets({version:'v4',auth});const book=await sheets.spreadsheets.get({spreadsheetId:id,fields:'properties.title,sheets.properties.title'});const tab=body.sheetName?.trim()||book.data.sheets?.[0]?.properties?.title;if(!tab)throw new Error('Sheet/tab tidak ditemukan.');
  const fetched=await sheets.spreadsheets.values.get({spreadsheetId:id,range:`'${tab.replace(/'/g,"''")}'`,valueRenderOption:'FORMATTED_VALUE'});const values=fetched.data.values||[];if(values.length<2)return NextResponse.json({error:'Sheet tidak berisi data laporan.'},{status:400});
  const headers=values[0].map(x=>String(x).trim()==='Data Petugas'?'Nama Petugas Input':String(x).trim());const required=['Submission ID'];const missing=required.filter(x=>!headers.includes(x));if(missing.length)return NextResponse.json({error:'Kolom wajib belum ditemukan: '+missing.join(', ')},{status:400});
  const rows:Row[]=values.slice(1).filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(headers.map((h,i)=>[h,String(r[i]??'')])));const ids=rows.map(r=>value(r,'Submission ID')).filter(Boolean);const {data:exists}=await admin.from('imported_laporan_kerusakan').select('id,external_submission_id').in('external_submission_id',ids);const known=new Map((exists||[]).map(r=>[r.external_submission_id,r.id]));const {data:sourceHistory}=await admin.from('imported_laporan_penanganan').select('source_fingerprint').in('laporan_import_id',(exists||[]).map(r=>r.id));const fingerprints=new Set((sourceHistory||[]).map(r=>r.source_fingerprint).filter(Boolean));let imported=0,skipped=0;const failed:{row:number;reason:string}[]=[];
  for(let i=0;i<rows.length;i++){
    const row=rows[i],external=value(row,'Submission ID'),rawPetugas=value(row,'Nama Petugas Input'),rawNip=value(row,'NIP');
    if(!external){failed.push({row:i+2,reason:'Submission ID kosong'});continue}
    const when=date(value(row,'Waktu Laporan WIB'))||date(value(row,'Waktu Laporan'))||date(value(row,'Submission time'))||new Date().toISOString();
    const petugas=!rawPetugas||/^\d{10,}$/.test(rawPetugas)?'Belum dilengkapi':rawPetugas,nip=rawNip||(/^\d{10,}$/.test(rawPetugas)?rawPetugas:'-'),damage=level(value(row,'Tingkat Kerusakan'))||'Belum diklasifikasikan';
    const sourceStatus=status(value(row,'Status Penanganan Plain')||value(row,'Status Penanganan'));
    const handlingTime=date(value(row,'Waktu Penanganan'));const handlingStaff=value(row,'Petugas yang Menangani');const handlingDocs=links(value(row,'Dokumentasi Penanganan'));const handlingNote=value(row,'Catatan Penanganan');
    const incomplete=[];if(petugas==='Belum dilengkapi')incomplete.push('Nama Petugas Input');if(nip==='-')incomplete.push('NIP');if(damage==='Belum diklasifikasikan')incomplete.push('Tingkat Kerusakan');
    const metadata={jenis_rambu:value(row,'Jenis Rambu')||null,dokumentasi_foto:value(row,'Dokumentasi Foto')||null,dokumentasi_penanganan:value(row,'Dokumentasi Penanganan')||null,waktu_penanganan:value(row,'Waktu Penanganan')||null,petugas_menangani:handlingStaff||null,catatan_penanganan:handlingNote||null,data_terbaru:value(row,'Data Terbaru')||null,sheet_url:`https://docs.google.com/spreadsheets/d/${id}`,sheet_tab:tab,field_belum_lengkap:incomplete};
    const nomor='IMPORT-'+when.slice(0,7).replace('-','')+'-'+createHash('sha256').update(external).digest('hex').slice(0,10).toUpperCase();
    const reportData={source_submission_time:date(value(row,'Submission time')),waktu_laporan:when,sumber_laporan:source(value(row,'Sumber Laporan')),nama_pelapor:value(row,'Nama Pelapor')||'Tidak diketahui',no_wa_pelapor:value(row,'Nomor Handphone')||null,nama_petugas_input:petugas,nip_petugas_input:nip,nama_jalan:value(row,'Nama Jalan'),kecamatan:value(row,'Kecamatan'),kelurahan:value(row,'Kelurahan Fix')||value(row,`Kelurahan (${value(row,'Kecamatan')})`),jenis_perlengkapan:value(row,'Jenis Kerusakan Perlengkapan Jalan'),tingkat_kerusakan:damage,deskripsi:value(row,'Keterangan / Deskripsi Kerusakan'),status_sumber:sourceStatus,import_metadata:metadata};
    let reportId=known.get(external);
    if(reportId){const {error:updateError}=await admin.from('imported_laporan_kerusakan').update(reportData).eq('id',reportId);if(updateError){failed.push({row:i+2,reason:updateError.message});continue}skipped++;}
    else{const {data:inserted,error:insertError}=await admin.from('imported_laporan_kerusakan').insert({...reportData,nomor_import:nomor,external_submission_id:external,imported_by:user.id,status:sourceStatus}).select('id').single();if(insertError||!inserted){failed.push({row:i+2,reason:insertError?.message||'Gagal menyimpan laporan'});continue}reportId=inserted.id;known.set(external,reportId);imported++;}
    const fingerprint=createHash('sha256').update(JSON.stringify([external,sourceStatus,handlingTime,handlingStaff,handlingDocs,handlingNote])).digest('hex');
    if(!fingerprints.has(fingerprint)){const {error:handlingError}=await admin.from('imported_laporan_penanganan').insert({laporan_import_id:reportId,status:sourceStatus,waktu_penanganan:handlingTime,petugas_menangani:handlingStaff||null,dokumentasi_urls:handlingDocs,catatan:handlingNote||null,updated_by:user.id,sumber_pembaruan:'import',source_fingerprint:fingerprint,created_at:date(value(row,'Data Terbaru'))||handlingTime||new Date().toISOString()});if(handlingError){failed.push({row:i+2,reason:'Riwayat penanganan: '+handlingError.message});continue}fingerprints.add(fingerprint);}
  }
  let folderUrl:string|undefined;
  if(imported>0){const drive=google.drive({version:'v3',auth}),parent=await getDriveParent(user.id);const day=new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Jakarta'});const folderName='Arsip Import '+day;const found=await drive.files.list({q:`'${parent}' in parents and name='${folderName}' and mimeType='application/vnd.google-apps.folder' and trashed=false`,fields:'files(id,webViewLink)'});const folder=found.data.files?.[0]||(await drive.files.create({requestBody:{name:folderName,mimeType:'application/vnd.google-apps.folder',parents:[parent]},fields:'id,webViewLink'})).data;folderUrl=folder.webViewLink||`https://drive.google.com/drive/folders/${folder.id}`;await drive.files.create({requestBody:{name:'Sumber Import - '+(book.data.properties?.title||id),mimeType:'application/vnd.google-apps.shortcut',parents:[folder.id!],shortcutDetails:{targetId:id}},fields:'id'});}
  await admin.from('google_sheet_import_sessions').insert({spreadsheet_id:id,spreadsheet_url:`https://docs.google.com/spreadsheets/d/${id}`,spreadsheet_title:book.data.properties?.title||null,drive_folder_url:folderUrl||null,imported_by:user.id,total_rows:rows.length,imported_rows:imported,skipped_rows:skipped,failed_rows:failed.length});
  return NextResponse.json({imported,skipped,failed,total:rows.length,tab,folderUrl,sheetUrl:`https://docs.google.com/spreadsheets/d/${id}`});
}catch(e){return NextResponse.json({error:'Import gagal: '+(e instanceof Error?e.message:'Kesalahan tidak diketahui')},{status:500});}}
