'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';

type Current={q:string;asal:string;status:string;kecamatan:string;jenis:string};
export function ReportFilters({current,districts,types}:{current:Current;districts:string[];types:string[]}){
  const [open,setOpen]=useState(false),count=[current.status,current.kecamatan,current.jenis].filter(Boolean).length;
  useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)};document.addEventListener('keydown',close);document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',close);document.body.style.overflow=''}},[open]);
  return <>
    <form method="get" className="hidden gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid md:grid-cols-2 xl:grid-cols-[minmax(220px,1.4fr)_1fr_1fr_1fr_auto]"><input type="hidden" name="asal" value={current.asal}/><Fields current={current} districts={districts} types={types}/><Buttons reset={Boolean(current.q||current.asal||count)}/></form>
    <div className="flex gap-2 md:hidden"><form method="get" className="min-w-0 flex-1"><input type="hidden" name="asal" value={current.asal}/><input type="hidden" name="status" value={current.status}/><input type="hidden" name="kecamatan" value={current.kecamatan}/><input type="hidden" name="jenis" value={current.jenis}/><input name="q" defaultValue={current.q} aria-label="Cari laporan" placeholder="Cari laporan..." className="h-11 w-full rounded-xl border border-slate-200 bg-white px-4 text-sm shadow-sm outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-50"/></form><button onClick={()=>setOpen(true)} className="relative h-11 rounded-xl border border-slate-200 bg-white px-4 text-sm font-semibold text-slate-700 shadow-sm">Filter{count>0&&<span className="ml-2 rounded-full bg-indigo-700 px-2 py-0.5 text-[10px] text-white">{count}</span>}</button></div>
    {open&&typeof document!=='undefined'&&createPortal(<div role="dialog" aria-modal="true" aria-label="Filter laporan" className="fixed inset-0 z-[100] bg-slate-950/45 backdrop-blur-sm md:hidden" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><form method="get" className="absolute bottom-0 max-h-[92dvh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl page-enter"><input type="hidden" name="asal" value={current.asal}/><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold">Filter Laporan</h2><p className="mt-1 text-xs text-slate-500">Tampilkan hanya data yang dibutuhkan.</p></div><button type="button" onClick={()=>setOpen(false)} className="grid h-9 w-9 place-items-center rounded-full bg-slate-100 text-xl text-slate-500">×</button></div><div className="space-y-4"><Fields current={current} districts={districts} types={types}/></div><div className="sticky bottom-0 mt-6 flex gap-2 border-t bg-white pt-4"><Link href="/laporan" className="grid h-11 flex-1 place-items-center rounded-xl border text-sm font-semibold text-slate-600">Reset</Link><button className="h-11 flex-1 rounded-xl bg-indigo-700 text-sm font-semibold text-white">Terapkan Filter</button></div></form></div>,document.body)}
  </>
}
function Fields({current,districts,types}:{current:Current;districts:string[];types:string[]}){return <><Field label="Cari laporan"><input name="q" defaultValue={current.q} placeholder="Nomor, pelapor, jalan..." className={input}/></Field><Field label="Status"><Select name="status" value={current.status} options={['Belum Ditangani','Dalam Proses','Selesai']} placeholder="Semua status"/></Field><Field label="Kecamatan"><Select name="kecamatan" value={current.kecamatan} options={districts} placeholder="Semua kecamatan"/></Field><Field label="Jenis fasilitas"><Select name="jenis" value={current.jenis} options={types} placeholder="Semua jenis"/></Field></>}
function Buttons({reset}:{reset:boolean}){return <div className="flex items-end gap-2"><button className="h-10 rounded-xl bg-indigo-700 px-4 text-sm font-semibold text-white">Tampilkan</button>{reset&&<Link href="/laporan" className="grid h-10 place-items-center rounded-xl border px-3 text-sm font-semibold text-slate-500">Reset</Link>}</div>}
const input='mt-1.5 h-10 w-full rounded-xl border border-slate-200 px-3 text-sm font-normal outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-50';
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs font-semibold text-slate-600">{label}{children}</label>}
function Select({name,value,options,placeholder}:{name:string;value:string;options:string[];placeholder:string}){return <select name={name} defaultValue={value} className={input+' bg-white text-slate-700'}><option value="">{placeholder}</option>{options.map(x=><option key={x}>{x}</option>)}</select>}
