'use client';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';

export type ReportListItem={id:string;nomor:string;waktu:string;pelapor:string;lokasi:string;wilayah?:string;jenis:string;tingkat:string;status:string;asal?:'Manual'|'Import';href:string;printHref?:string;deskripsi?:string;petugas?:string};
const level=(v:string)=>v==='Darurat'?'bg-rose-600 text-white ring-rose-600':v==='Berat'?'bg-rose-50 text-rose-700 ring-rose-100':v==='Sedang'?'bg-amber-50 text-amber-700 ring-amber-100':'bg-emerald-50 text-emerald-700 ring-emerald-100';
const state=(v:string)=>v==='Selesai'?'bg-emerald-500':v==='Dalam Proses'?'bg-blue-500':'bg-amber-500';
const stateText=(v:string)=>v==='Selesai'?'text-emerald-700':v==='Dalam Proses'?'text-blue-700':'text-amber-700';
const stamp=(v:string)=>new Date(v).toLocaleString('id-ID',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Jakarta'});
const source=(v?:string)=>v==='Import'?'bg-cyan-50 text-cyan-700 ring-cyan-100':'bg-indigo-50 text-indigo-700 ring-indigo-100';

export function ReportList({items,empty='Belum ada laporan.',compact=false}:{items:ReportListItem[];empty?:string;compact?:boolean}){
  const router=useRouter(),[preview,setPreview]=useState<ReportListItem|null>(null);
  useEffect(()=>{if(!preview)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setPreview(null)};document.addEventListener('keydown',close);document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',close);document.body.style.overflow=''}},[preview]);
  const open=(item:ReportListItem)=>router.push(item.href);
  if(!items.length)return <Empty text={empty}/>;
  return <div>
    {!compact&&<div className="hidden grid-cols-[minmax(0,1.15fr)_minmax(0,1.25fr)_minmax(150px,.65fr)_150px] gap-5 border-b bg-slate-50/80 px-5 py-3 text-[10px] font-bold uppercase tracking-[.1em] text-slate-400 xl:grid"><span>Laporan</span><span>Lokasi & Jenis</span><span>Kondisi</span><span className="text-right">Aksi</span></div>}
    <div className="divide-y divide-slate-100">{items.map(item=><article role="link" tabIndex={0} aria-label={`Buka ${item.nomor}`} key={(item.asal||'')+item.id} onClick={()=>open(item)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(item)}}} className={'group relative cursor-pointer border-l-4 p-4 outline-none transition duration-200 hover:bg-indigo-50/50 focus-visible:bg-indigo-50 sm:p-5 '+(item.tingkat==='Darurat'?'border-l-rose-500':item.tingkat==='Berat'?'border-l-rose-200':'border-l-transparent')+(compact?' flex flex-col gap-4 sm:grid sm:grid-cols-2':' grid gap-4 md:grid-cols-2 xl:grid-cols-[minmax(0,1.15fr)_minmax(0,1.25fr)_minmax(150px,.65fr)_150px] xl:items-center xl:gap-5')}>
      <Identity item={item}/><Location item={item}/><Condition item={item}/><Actions item={item} onPreview={()=>setPreview(item)}/>
      {!compact&&<span className="pointer-events-none absolute right-3 top-3 translate-x-1 text-sm text-indigo-400 opacity-0 transition group-hover:translate-x-0 group-hover:opacity-100 xl:hidden">→</span>}
    </article>)}</div>
    {preview&&typeof document!=='undefined'&&createPortal(<Preview item={preview} close={()=>setPreview(null)}/>,document.body)}
  </div>
}

function Identity({item}:{item:ReportListItem}){return <div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={'rounded-md px-2 py-1 text-[10px] font-bold uppercase tracking-[.08em] ring-1 '+source(item.asal)}>{item.asal||'Manual'}</span><span className="break-words text-sm font-bold leading-5 text-indigo-700">{item.nomor}</span></div><p className="mt-2 truncate text-xs text-slate-500">{stamp(item.waktu)} <span className="text-slate-300">•</span> {item.pelapor||'Tidak diketahui'}</p></div>}
function Location({item}:{item:ReportListItem}){return <div className="min-w-0"><p className="font-bold leading-5 text-slate-900">{item.lokasi}</p>{item.wilayah&&<p className="mt-1 truncate text-xs text-slate-500">{item.wilayah}</p>}<p className="mt-2 truncate text-sm font-medium text-slate-600">{item.jenis}</p></div>}
function Condition({item}:{item:ReportListItem}){return <div className="flex flex-wrap items-center gap-2 xl:flex-col xl:items-start"><span className={'rounded-full px-2.5 py-1 text-xs font-semibold ring-1 '+level(item.tingkat)}>{item.tingkat}</span><span className={'flex items-center gap-1.5 text-xs font-semibold '+stateText(item.status)}><i className={'h-2 w-2 rounded-full '+state(item.status)}/>{item.status}</span></div>}
function Actions({item,onPreview}:{item:ReportListItem;onPreview:()=>void}){return <div onClick={e=>e.stopPropagation()} className="flex items-center gap-2 xl:justify-end"><button type="button" onClick={onPreview} aria-label="Lihat ringkasan" title="Lihat ringkasan" className="grid h-10 w-10 place-items-center rounded-lg border border-slate-200 bg-white text-slate-500 transition hover:border-indigo-200 hover:bg-indigo-50 hover:text-indigo-700">◉</button><Link href={item.href} className="inline-flex h-10 items-center justify-center rounded-lg bg-indigo-700 px-3.5 text-xs font-semibold text-white shadow-sm transition hover:bg-indigo-800">Detail</Link></div>}
function Preview({item,close}:{item:ReportListItem;close:()=>void}){return <div role="dialog" aria-modal="true" aria-label="Ringkasan laporan" className="fixed inset-0 z-[100] bg-slate-950/45 backdrop-blur-sm" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><aside className="absolute bottom-0 right-0 flex max-h-[92dvh] w-full flex-col overflow-hidden rounded-t-3xl bg-white shadow-2xl page-enter sm:inset-y-0 sm:max-h-none sm:max-w-md sm:rounded-none"><div className="flex-1 overflow-y-auto p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><span className={'rounded-md px-2 py-1 text-[10px] font-bold uppercase ring-1 '+source(item.asal)}>{item.asal||'Manual'}</span><h2 className="mt-3 break-words text-lg font-bold text-indigo-700">{item.nomor}</h2><p className="mt-1 text-xs text-slate-500">{stamp(item.waktu)}</p></div><button onClick={close} aria-label="Tutup ringkasan" className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-slate-100 text-xl text-slate-500">×</button></div><div className="mt-6 rounded-2xl bg-slate-50 p-4"><h3 className="break-words font-bold text-slate-900">{item.lokasi||'Lokasi belum tersedia'}</h3><p className="mt-1 text-sm text-slate-500">{item.wilayah||'Wilayah belum tersedia'}</p><p className="mt-3 text-sm font-semibold text-slate-700">{item.jenis||'Jenis belum tersedia'}</p></div><dl className="mt-6 space-y-4 text-sm"><Info label="Pelapor" value={item.pelapor||'Tidak diketahui'}/><Info label="Tingkat kerusakan" value={item.tingkat||'-'}/><Info label="Status" value={item.status||'-'}/><Info label="Petugas input" value={item.petugas||'Belum tersedia'}/><Info label="Deskripsi" value={item.deskripsi||'Belum tersedia'}/></dl></div><div className="flex shrink-0 gap-2 border-t bg-white p-4 sm:px-7"><button onClick={close} className="h-11 flex-1 rounded-xl border text-sm font-semibold text-slate-600">Tutup</button><Link href={item.href} className="grid h-11 flex-1 place-items-center rounded-xl bg-indigo-700 text-sm font-semibold text-white">Kelola Laporan</Link></div></aside></div>}
function Info({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-medium text-slate-400">{label}</dt><dd className="mt-1 leading-6 text-slate-700">{value}</dd></div>}
function Empty({text}:{text:string}){return <div className="px-5 py-14 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-slate-100 text-xl text-slate-400">○</div><p className="mt-3 text-sm text-slate-500">{text}</p></div>}
