import { NextResponse } from 'next/server';
import { google } from 'googleapis';
import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { getGoogleOAuth } from '@/lib/google-oauth';
const allowed=['Belum Ditangani','Dalam Proses','Selesai'];
function col(index:number){let out='';for(let n=index+1;n>0;n=Math.floor((n-1)/26))out=String.fromCharCode(65+(n-1)%26)+out;return out;}
function msg(e:unknown){if(e instanceof Error)return e.message;if(typeof e==='object'&&e){const x=e as {response?:{data?:{error?:{message?:string}}};message?:string};return x.response?.data?.error?.message||x.message||'Kesalahan tidak diketahui';}return String(e||'Kesalahan tidak diketahui');}

export async function POST(req:Request){try{
  const body=await req.json() as {laporanId?:string;status?:string;waktuPenanganan?:string;petugas?:string;dokumentasi?:string;catatan?:string};if(!body.laporanId||!body.status||!allowed.includes(body.status))return NextResponse.json({error:'Data penanganan tidak valid.'},{status:400});
  const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return NextResponse.json({error:'Sesi login tidak valid.'},{status:401});const admin=createAdminClient();const [{data:report,error:reportError},{data:recap,error:recapError},{data:token,error:tokenError}]=await Promise.all([admin.from('imported_laporan_kerusakan').select('id,external_submission_id').eq('id',body.laporanId).single(),admin.from('google_import_recap_sheets').select('spreadsheet_id,spreadsheet_url').eq('user_id',user.id).maybeSingle(),admin.from('google_oauth_tokens').select('refresh_token').eq('user_id',user.id).maybeSingle()]);if(reportError||!report)throw reportError||new Error('Data import tidak ditemukan.');if(recapError)throw recapError;if(!recap)return NextResponse.json({error:'Rekap import belum dibuat. Klik Export Data Import pada Arsip Data Import terlebih dahulu.'},{status:409});if(tokenError)throw tokenError;if(!token)return NextResponse.json({error:'Google Drive belum terhubung.',connectUrl:'/api/google/connect'},{status:409});
  const auth=getGoogleOAuth();auth.setCredentials({refresh_token:token.refresh_token});const sheets=google.sheets({version:'v4',auth});const book=await sheets.spreadsheets.get({spreadsheetId:recap.spreadsheet_id,fields:'sheets.properties.title'});const tab=book.data.sheets?.[0]?.properties?.title||'Sheet1';const safe=tab.replace(/'/g,"''");const fetched=await sheets.spreadsheets.values.get({spreadsheetId:recap.spreadsheet_id,range:`'${safe}'`,valueRenderOption:'FORMATTED_VALUE'});const values=fetched.data.values||[];const headers=(values[3]||[]).map(x=>String(x).trim());const idIndex=headers.indexOf('Submission ID');if(idIndex<0)throw new Error('Kolom Submission ID tidak ditemukan pada Sheet rekap. Silakan export ulang data import.');const rowIndex=values.findIndex((row,index)=>index>3&&String(row[idIndex]??'').trim()===report.external_submission_id);if(rowIndex<4)throw new Error('Data belum terdapat pada Sheet rekap. Silakan export ulang data import.');
  const targets:Record<string,string>={'Status Penanganan':body.status,'Waktu Penanganan':body.waktuPenanganan||'','Petugas yang Menangani':body.petugas||'','Dokumentasi Penanganan':body.dokumentasi||'','Catatan Penanganan':body.catatan||''};await sheets.spreadsheets.values.batchUpdate({spreadsheetId:recap.spreadsheet_id,requestBody:{valueInputOption:'USER_ENTERED',data:Object.entries(targets).map(([name,value])=>{const index=headers.indexOf(name);if(index<0)throw new Error(`Kolom ${name} tidak ditemukan. Silakan export ulang data import.`);return {range:`'${safe}'!${col(index)}${rowIndex+1}`,values:[[value]]};})}});
  const docs=(body.dokumentasi||'').split('\n').map(x=>x.trim()).filter(Boolean);const waktu=body.waktuPenanganan?new Date(body.waktuPenanganan+':00+07:00').toISOString():null;const {error:historyError}=await admin.from('imported_laporan_penanganan').insert({laporan_import_id:body.laporanId,status:body.status,waktu_penanganan:waktu,petugas_menangani:body.petugas||null,dokumentasi_urls:docs,catatan:body.catatan||null,updated_by:user.id});if(historyError)throw historyError;const {error:updateError}=await admin.from('imported_laporan_kerusakan').update({status:body.status}).eq('id',body.laporanId);if(updateError)throw updateError;return NextResponse.json({ok:true,message:'Penanganan tersimpan dan Rekap Data Import berhasil diperbarui.',sheetUrl:recap.spreadsheet_url});
}catch(e){return NextResponse.json({error:'Gagal menyimpan penanganan: '+msg(e)},{status:500});}}
