import {createClient} from '@/lib/supabase/server';
import {HandlingForm} from './handling-form';

export default async function DetailImport({params}:{params:{id:string}}){
  const s=createClient();const [{data:report},{data:history}]=await Promise.all([s.from('imported_laporan_kerusakan').select('*').eq('id',params.id).single(),s.from('imported_laporan_penanganan').select('*').eq('laporan_import_id',params.id).order('created_at',{ascending:false})]);
  if(!report)return <p>Data import tidak ditemukan.</p>;
  const fields=[['Waktu Laporan',new Date(report.waktu_laporan).toLocaleString('id-ID')],['Pelapor',report.nama_pelapor||'Tidak diketahui'],['Jenis Perlengkapan',report.jenis_perlengkapan],['Tingkat Kerusakan',report.tingkat_kerusakan],['Deskripsi',report.deskripsi],['Petugas Input',report.nama_petugas_input+' / '+report.nip_petugas_input],['Status Saat Ini',report.status]];
  return <section className="mx-auto max-w-5xl pb-20 sm:pb-0"><header className="rounded-2xl bg-gradient-to-r from-cyan-800 to-blue-700 p-6 text-white"><p className="text-xs font-bold tracking-[.16em] text-cyan-100">DETAIL DATA IMPORT</p><h1 className="mt-2 text-2xl font-bold">{report.nomor_import}</h1><p className="mt-1 text-sm text-cyan-50">{report.nama_jalan} · {report.kelurahan}, {report.kecamatan}</p></header>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold">Data Laporan dari Sheet</h2><dl className="mt-4 space-y-4 text-sm">{fields.map(([k,v])=><div key={k}><dt className="text-xs text-slate-400">{k}</dt><dd className="mt-1 whitespace-pre-wrap font-medium leading-6 text-slate-700">{v}</dd></div>)}</dl></article><div id="penanganan" className="scroll-mt-24"><HandlingForm reportId={report.id} initialStatus={report.status}/></div></div>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold">Riwayat Penanganan</h2><p className="mt-1 text-sm text-slate-500">Memuat pembaruan dari Sheet sumber dan pembaruan manual petugas.</p><div className="mt-5 space-y-0">{history?.map((h,index)=><div key={h.id} className="flex gap-3"><div className="flex flex-col items-center"><span className={'mt-1.5 h-2.5 w-2.5 rounded-full ring-4 '+(h.sumber_pembaruan==='import'?'bg-cyan-500 ring-cyan-50':'bg-indigo-500 ring-indigo-50')}/>{index<(history?.length||0)-1&&<span className="h-full w-px bg-slate-200"/>}</div><div className="min-w-0 pb-6 text-sm"><div className="flex flex-wrap justify-between gap-2"><div className="flex items-center gap-2"><b>{h.status}</b><span className={h.sumber_pembaruan==='import'?'rounded-full bg-cyan-100 px-2 py-0.5 text-xs font-semibold text-cyan-800':'rounded-full bg-indigo-100 px-2 py-0.5 text-xs font-semibold text-indigo-800'}>{h.sumber_pembaruan==='import'?'Sumber Import':'Manual'}</span></div><span className="text-xs text-slate-500">{new Date(h.created_at).toLocaleString('id-ID')}</span></div><p className="mt-2 text-slate-600">{h.petugas_menangani||'Petugas belum diisi'} · {h.waktu_penanganan?new Date(h.waktu_penanganan).toLocaleString('id-ID'):'Waktu belum diisi'}</p>{h.catatan&&<p className="mt-2 leading-6 text-slate-600">{h.catatan}</p>}{h.dokumentasi_urls?.length>0&&<div className="mt-2 flex flex-wrap gap-2">{h.dokumentasi_urls.map((url:string,n:number)=><a key={url+n} href={url} target="_blank" rel="noreferrer" className="text-xs font-semibold text-cyan-700 hover:underline">Dokumentasi {n+1} ↗</a>)}</div>}</div></div>)}{!history?.length&&<p className="text-sm text-slate-500">Belum ada riwayat penanganan.</p>}</div></section>
    <div className="fixed inset-x-0 bottom-0 z-30 border-t bg-white/95 p-3 shadow-[0_-8px_24px_rgba(15,23,42,.08)] backdrop-blur sm:hidden"><a href="#penanganan" className="grid h-11 place-items-center rounded-xl bg-indigo-700 text-sm font-semibold text-white">Perbarui Penanganan</a></div>
  </section>
}
