import Link from 'next/link';
import {createClient} from '@/lib/supabase/server';
import {HandlingForm} from './handling-form';

export default async function Detail({params}:{params:{id:string}}){
  const s=createClient();const [{data:r},{data:h}]=await Promise.all([s.from('laporan_kerusakan').select('*').eq('id',params.id).single(),s.from('laporan_penanganan').select('*').eq('laporan_id',params.id).order('created_at',{ascending:false})]);
  if(!r)return <p>Laporan tidak ditemukan.</p>;
  const fields=[['Waktu Laporan',new Date(r.waktu_laporan||r.created_at).toLocaleString('id-ID')],['Pelapor',r.nama_pelapor||'Tidak diketahui'],['Jenis Perlengkapan',r.jenis_perlengkapan],['Kategori Rambu',r.jenis_rambu||'-'],['Tingkat Kerusakan',r.tingkat_kerusakan],['Deskripsi',r.deskripsi],['Petugas Input',r.nama_petugas_input+' / '+r.nip_petugas_input],['Status',r.status]];
  return <section className="mx-auto max-w-5xl pb-20 sm:pb-0"><header className="rounded-2xl bg-gradient-to-r from-indigo-900 to-blue-700 p-6 text-white"><p className="text-xs font-bold tracking-widest text-cyan-200">LAPORAN MANUAL</p><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-bold">{r.nomor_laporan}</h1><Link href={'/laporan/cetak?id='+r.id} className="hidden rounded-lg bg-white px-3 py-2 text-sm font-semibold text-indigo-700 sm:block">Cetak Laporan</Link></div><p className="mt-1 text-sm text-indigo-100">{r.nama_jalan} · {r.kelurahan}, {r.kecamatan}</p></header>
    <div className="mt-6 grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border bg-white p-6 shadow-sm"><h2 className="font-bold">Data Laporan</h2><dl className="mt-4 space-y-4 text-sm">{fields.map(([k,v])=><div key={k}><dt className="text-xs text-slate-400">{k}</dt><dd className="mt-1 whitespace-pre-wrap font-medium leading-6 text-slate-700">{v}</dd></div>)}</dl></article><div id="penanganan" className="scroll-mt-24"><HandlingForm reportId={r.id} initialStatus={r.status}/></div></div>
    <section className="mt-6 rounded-2xl border bg-white p-6 shadow-sm"><h2 className="font-bold">Riwayat Penanganan</h2><div className="mt-5 space-y-0">{h?.map((x,index)=><div key={x.id} className="flex gap-3"><div className="flex flex-col items-center"><span className="mt-1.5 h-2.5 w-2.5 rounded-full bg-indigo-500 ring-4 ring-indigo-50"/>{index<(h?.length||0)-1&&<span className="h-full w-px bg-slate-200"/>}</div><div className="min-w-0 pb-6 text-sm"><div className="flex flex-wrap justify-between gap-2"><b>{x.status}</b><span className="text-xs text-slate-500">{new Date(x.created_at).toLocaleString('id-ID')}</span></div><p className="mt-2 text-slate-600">{x.petugas_menangani||'Petugas belum diisi'} · {x.waktu_penanganan?new Date(x.waktu_penanganan).toLocaleString('id-ID'):'Waktu belum diisi'}</p>{x.catatan&&<p className="mt-2 leading-6 text-slate-600">{x.catatan}</p>}</div></div>)}{!h?.length&&<p className="text-sm text-slate-500">Belum ada riwayat penanganan.</p>}</div></section>
    <div className="no-print fixed inset-x-0 bottom-0 z-30 flex gap-2 border-t bg-white/95 p-3 shadow-[0_-8px_24px_rgba(15,23,42,.08)] backdrop-blur sm:hidden"><Link href={'/laporan/cetak?id='+r.id} className="grid h-11 flex-1 place-items-center rounded-xl border text-sm font-semibold text-slate-600">Cetak</Link><a href="#penanganan" className="grid h-11 flex-[1.6] place-items-center rounded-xl bg-indigo-700 text-sm font-semibold text-white">Perbarui Penanganan</a></div>
  </section>
}
