'use client';

import { useState } from 'react';
import { supabase } from '@/lib/supabase/client';
import { createReport } from '../actions';
import { useRouter } from 'next/navigation';

type Ref = { id: string; nama: string };
const input = 'mt-1.5 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-800 outline-none transition placeholder:text-slate-400 focus:border-blue-500 focus:ring-4 focus:ring-blue-50 disabled:cursor-not-allowed disabled:bg-slate-50';
const Label = ({ children, hint }: { children: React.ReactNode; hint?: string }) => <label className="block text-sm font-medium text-slate-700">{children}{hint && <span className="ml-1 font-normal text-slate-400">{hint}</span>}</label>;

export function ReportForm({ profile, kecamatan, jenis, jenisRambu }: { profile: { nama: string; nip: string }; kecamatan: Ref[]; jenis: Ref[]; jenisRambu: Ref[] }) {
  const router = useRouter();
  const [kec, setKec] = useState(''); const [kel, setKel] = useState<Ref[]>([]); const [jenisId, setJenisId] = useState(''); const [files, setFiles] = useState<File[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  async function changeKec(id: string) { setKec(id); setKel([]); if (id) { const { data } = await supabase.from('ref_kelurahan').select('id,nama').eq('kecamatan_id', id).order('nama'); setKel(data ?? []); } }
  function pick(list: FileList | null) { if (!list) return; const next = [...files, ...Array.from(list)]; if (next.length > 5) return setError('Maksimal 5 foto dapat diunggah.'); if (next.some(f => !['image/jpeg', 'image/png'].includes(f.type) || f.size > 5 * 1024 * 1024)) return setError('Gunakan foto JPG, JPEG, atau PNG dengan ukuran maksimal 5 MB.'); setError(''); setFiles(next); }
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setLoading(true); setError(''); const form = new FormData(e.currentTarget); let paths: string[] = []; if (files.length) { const upload = new FormData(); files.forEach(f => upload.append('files', f)); const r = await fetch('/api/upload', { method: 'POST', body: upload }); const j = await r.json(); if (!r.ok) { setError(j.error); setLoading(false); return; } paths = j.paths; } const result = await createReport(Object.fromEntries(form), paths); if (result.error) { if (paths.length) await fetch('/api/upload', { method: 'DELETE', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ paths }) }); setError(result.error); setLoading(false); return; } router.push('/laporan'); }
  return <form onSubmit={submit} className="mx-auto max-w-5xl space-y-5 pb-10">
    <header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-medium text-blue-700">LAPORAN BARU</p><h2 className="mt-1 text-2xl font-bold tracking-tight">Tambah Laporan Kerusakan</h2><p className="mt-1 text-sm text-slate-500">Lengkapi informasi di bawah. Kolom bertanda <span className="text-rose-600">*</span> wajib diisi.</p></div><button disabled={loading} className="order-first w-full rounded-lg bg-blue-700 px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-800 disabled:opacity-60 sm:order-none sm:w-auto">{loading ? 'Menyimpan…' : 'Simpan Laporan'}</button></header>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><div className="mb-5"><h3 className="font-semibold text-slate-900">1. Informasi Pelapor</h3><p className="mt-1 text-sm text-slate-500">Sumber, waktu laporan, dan identitas pihak yang melaporkan.</p></div><div className="grid gap-4 md:grid-cols-2"><div><Label>Sumber laporan <span className="text-rose-600">*</span></Label><select name="sumber_laporan" className={input}>{['Masyarakat', 'Petugas Lapangan', 'Kepolisian', 'Lainnya'].map(x => <option key={x}>{x}</option>)}</select></div><div><Label>Waktu laporan <span className="text-rose-600">*</span></Label><input name="waktu_laporan" type="datetime-local" required defaultValue={new Date(Date.now()+7*3600000).toISOString().slice(0,16)} className={input}/></div><div><Label hint="opsional">Nama pelapor</Label><input name="nama_pelapor" placeholder="Kosongkan jika tidak diketahui" className={input}/></div><div><Label hint="opsional">No. WhatsApp</Label><input name="no_wa_pelapor" inputMode="tel" placeholder="08… / 628… / +628…" className={input}/></div></div></section>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm md:p-6">
      <div className="mb-5"><h3 className="font-semibold text-slate-900">2. Lokasi & Perlengkapan</h3><p className="mt-1 text-sm text-slate-500">Pastikan lokasi kerusakan dipilih secara tepat.</p></div>
      <div className="grid gap-4 md:grid-cols-2">
        <div className="md:col-span-2"><Label>Nama jalan <span className="text-rose-600">*</span></Label><input name="nama_jalan" required placeholder="Contoh: Jalan Pahlawan" className={input}/></div>
        <div><Label>Kecamatan <span className="text-rose-600">*</span></Label><select name="kecamatan_id" required value={kec} onChange={e => changeKec(e.target.value)} className={input}><option value="">Pilih kecamatan</option>{kecamatan.map(x => <option key={x.id} value={x.id}>{x.nama}</option>)}</select></div>
        <div><Label>Kelurahan <span className="text-rose-600">*</span></Label><select name="kelurahan_id" required disabled={!kec} className={input}><option value="">{kec ? 'Pilih kelurahan' : 'Pilih kecamatan terlebih dahulu'}</option>{kel.map(x => <option key={x.id} value={x.id}>{x.nama}</option>)}</select></div>
        <div><Label>Jenis perlengkapan <span className="text-rose-600">*</span></Label><select name="jenis_id" required value={jenisId} onChange={e=>setJenisId(e.target.value)} className={input}><option value="">Pilih jenis perlengkapan</option>{jenis.map(x => <option key={x.id} value={x.id}>{x.nama}</option>)}</select></div>
        <div><Label>Tingkat kerusakan <span className="text-rose-600">*</span></Label><select name="tingkat_kerusakan" required className={input}><option value="">Pilih tingkat kerusakan</option>{['Ringan', 'Sedang', 'Berat', 'Darurat'].map(x => <option key={x}>{x}</option>)}</select></div>
        {jenis.find(x=>x.id===jenisId)?.nama==='Rambu Lalu Lintas'&&<div><Label>Kategori rambu <span className="text-rose-600">*</span></Label><select name="jenis_rambu" required className={input}><option value="">Pilih kategori rambu</option>{jenisRambu.map(x=><option key={x.id} value={x.nama}>{x.nama}</option>)}</select></div>}
        <div className="md:col-span-2"><Label>Deskripsi kerusakan <span className="text-rose-600">*</span></Label><textarea name="deskripsi" required placeholder="Jelaskan jenis kerusakan, kondisi saat ini, dan informasi penting lain…" className={input+' min-h-28 resize-y'}/></div>
      </div>
    </section>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><div className="mb-5"><h3 className="font-semibold text-slate-900">3. Petugas Input</h3><p className="mt-1 text-sm text-slate-500">Diisi otomatis dari profil Anda dan dapat dikoreksi bila diperlukan.</p></div><div className="grid gap-4 md:grid-cols-2"><div><Label>Nama petugas <span className="text-rose-600">*</span></Label><input name="nama_petugas_input" required defaultValue={profile.nama} className={input}/></div><div><Label>NIP petugas <span className="text-rose-600">*</span></Label><input name="nip_petugas_input" required defaultValue={profile.nip} inputMode="numeric" className={input}/></div></div></section>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><div className="mb-5"><h3 className="font-semibold text-slate-900">4. Dokumentasi</h3><p className="mt-1 text-sm text-slate-500">Opsional · Maksimal 5 foto, format JPG/JPEG/PNG, masing-masing maksimal 5 MB.</p></div><div onDrop={e => { e.preventDefault(); pick(e.dataTransfer.files); }} onDragOver={e => e.preventDefault()} className="rounded-xl border-2 border-dashed border-slate-200 bg-slate-50 px-5 py-8 text-center transition hover:border-blue-300 hover:bg-blue-50"><p className="text-sm font-medium text-slate-700">Tarik foto ke area ini</p><p className="mt-1 text-xs text-slate-500">atau</p><label className="mt-3 inline-block cursor-pointer rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 shadow-sm hover:bg-slate-50">Pilih foto<input className="hidden" type="file" accept="image/jpeg,image/png" multiple onChange={e => pick(e.target.files)}/></label></div>{files.length > 0 && <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{files.map((file, index) => <div className="flex items-center justify-between gap-2 rounded-lg border border-slate-200 px-3 py-2" key={file.name + index}><span className="truncate text-sm text-slate-600">{file.name}</span><button type="button" onClick={() => setFiles(files.filter((_, i) => i !== index))} className="shrink-0 text-sm font-medium text-rose-600 hover:text-rose-800">Hapus</button></div>)}</div>}</section>
    <details className="group rounded-xl border border-blue-100 bg-blue-50/40 shadow-sm">
      <summary className="flex cursor-pointer list-none items-center justify-between gap-3 p-5 md:p-6"><div><h3 className="font-semibold text-slate-900">5. Penanganan Awal <span className="font-normal text-slate-400">(opsional)</span></h3><p className="mt-1 text-sm text-slate-500">Lewati bagian ini jika laporan belum ditangani.</p></div><span className="shrink-0 rounded-lg border border-blue-200 bg-white px-3 py-2 text-xs font-semibold text-blue-700 group-open:hidden">+ Isi Penanganan Awal</span><span className="hidden shrink-0 text-sm font-semibold text-blue-700 group-open:block">Tutup</span></summary>
      <div className="grid gap-4 border-t border-blue-100 p-5 md:grid-cols-2 md:p-6"><div><Label>Status penanganan</Label><select name="status" defaultValue="Belum Ditangani" className={input}>{['Belum Ditangani','Dalam Proses','Selesai'].map(x=><option key={x}>{x}</option>)}</select></div><div><Label hint="opsional">Waktu penanganan</Label><input name="waktu_penanganan" type="datetime-local" className={input}/></div><div><Label hint="opsional">Petugas yang menangani</Label><input name="petugas_menangani" placeholder="Nama petugas atau tim" className={input}/></div><div><Label hint="satu URL per baris">Dokumentasi penanganan</Label><textarea name="dokumentasi_penanganan" placeholder="https://drive.google.com/..." className={input+' min-h-24 resize-y'}/></div><div className="md:col-span-2"><Label hint="opsional">Catatan penanganan</Label><textarea name="catatan_penanganan" placeholder="Tindakan, hasil pemeriksaan, atau kebutuhan tindak lanjut" className={input+' min-h-24 resize-y'}/></div></div>
    </details>
    {error && <div role="alert" className="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
    <div className="sticky bottom-3 flex justify-end rounded-xl border border-slate-200 bg-white/95 p-3 shadow-lg backdrop-blur sm:p-4"><button disabled={loading} className="w-full rounded-lg bg-blue-700 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-blue-800 disabled:opacity-60 sm:w-auto">{loading ? 'Menyimpan…' : 'Simpan Laporan'}</button></div>
  </form>;
}
