import {NextResponse} from 'next/server';import {google,drive_v3} from 'googleapis';import {createClient} from '@/lib/supabase/server';import {createAdminClient} from '@/lib/supabase/admin';import {getGoogleOAuth} from '@/lib/google-oauth';import {getDriveParent} from '@/lib/google-drive-settings';import {recapPeriod} from '@/lib/recap-period';
const reason=(e:unknown)=>e instanceof Error?e.message:typeof e==='object'&&e&&'message' in e?String(e.message):String(e||'Kesalahan tidak diketahui');const rgb=(r:number,g:number,b:number)=>({red:r/255,green:g/255,blue:b/255});
async function folder(drive:drive_v3.Drive,parent:string,name:string){const safe=name.replace(/'/g,"\\'");const found=await drive.files.list({q:`'${parent}' in parents and name='${safe}' and mimeType='application/vnd.google-apps.folder' and trashed=false`,fields:'files(id)'});return found.data.files?.[0]?.id||(await drive.files.create({requestBody:{name,mimeType:'application/vnd.google-apps.folder',parents:[parent]},fields:'id'})).data.id!}
export async function GET(req:Request){try{
 const period=recapPeriod(new URL(req.url).searchParams),s=createClient(),{data:{user}}=await s.auth.getUser();if(!user)return NextResponse.redirect(new URL('/login',req.url));const admin=createAdminClient(),{data:token,error:tokenError}=await admin.from('google_oauth_tokens').select('refresh_token').eq('user_id',user.id).maybeSingle();if(tokenError)throw tokenError;if(!token)return NextResponse.redirect(new URL('/api/google/connect?returnTo=/laporan/rekap',req.url));
 let manual=admin.from('laporan_kerusakan').select('*').order('waktu_laporan',{ascending:false}),imports=admin.from('imported_laporan_kerusakan').select('*').order('waktu_laporan',{ascending:false});if(period.start&&period.end){manual=manual.gte('waktu_laporan',period.start).lt('waktu_laporan',period.end);imports=imports.gte('waktu_laporan',period.start).lt('waktu_laporan',period.end)}
 const [{data:m,error:me},{data:i,error:ie},{data:mh},{data:ih},{data:saved}]=await Promise.all([manual,imports,admin.from('laporan_penanganan').select('*').order('created_at',{ascending:false}),admin.from('imported_laporan_penanganan').select('*').order('created_at',{ascending:false}),admin.from('google_combined_recap_sheets').select('*').eq('user_id',user.id).eq('recap_type',period.type).eq('period_key',period.key).maybeSingle()]);if(me)throw me;if(ie)throw ie;
 const manualHistory=new Map<string,Record<string,unknown>>(),importHistory=new Map<string,Record<string,unknown>>();for(const h of mh||[])if(!manualHistory.has(h.laporan_id))manualHistory.set(h.laporan_id,h);for(const h of ih||[])if(!importHistory.has(h.laporan_import_id))importHistory.set(h.laporan_import_id,h);
 const records=[...(m||[]).map(r=>({r,h:manualHistory.get(r.id),asal:'Manual',nomor:r.nomor_laporan,waktu:r.waktu_laporan||r.created_at,submission:''})),...(i||[]).map(r=>({r,h:importHistory.get(r.id),asal:'Google Sheet Import',nomor:r.nomor_import,waktu:r.waktu_laporan,submission:r.external_submission_id}))].sort((a,b)=>new Date(b.waktu).getTime()-new Date(a.waktu).getTime());
 const values=[['DINAS PERHUBUNGAN KOTA MADIUN'],['REKAP GABUNGAN • '+period.label.toUpperCase()],[`Total Data: ${records.length} • Diperbarui: ${new Date().toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB`],['No','Asal Data','Nomor Laporan','Submission ID','Waktu Laporan','Sumber','Nama Pelapor','No WA','Nama Petugas Input','NIP','Nama Jalan','Kecamatan','Kelurahan','Jenis Perlengkapan','Jenis Rambu','Tingkat Kerusakan','Deskripsi','Status Penanganan','Waktu Penanganan','Petugas yang Menangani','Dokumentasi Penanganan','Catatan Penanganan'],...records.map((x,n)=>{const r=x.r,h=x.h as {waktu_penanganan?:string;petugas_menangani?:string;dokumentasi_urls?:string[];catatan?:string}|undefined,meta=r.import_metadata as {jenis_rambu?:string}|undefined;return [n+1,x.asal,x.nomor,x.submission,new Date(x.waktu).toLocaleString('id-ID'),r.sumber_laporan,r.nama_pelapor,r.no_wa_pelapor||'',r.nama_petugas_input,r.nip_petugas_input,r.nama_jalan,r.kecamatan,r.kelurahan,r.jenis_perlengkapan,r.jenis_rambu||meta?.jenis_rambu||'',r.tingkat_kerusakan,r.deskripsi,r.status,h?.waktu_penanganan?new Date(h.waktu_penanganan).toLocaleString('id-ID'):'',h?.petugas_menangani||'',h?.dokumentasi_urls?.join('\n')||'',h?.catatan||'']})];
 const auth=getGoogleOAuth();auth.setCredentials({refresh_token:token.refresh_token});const drive=google.drive({version:'v3',auth});let fileId=saved?.spreadsheet_id||'',url=saved?.spreadsheet_url||'',folderId=saved?.folder_id||'';
 if(!fileId){const root=await getDriveParent(user.id),recapRoot=await folder(drive,root,'Rekap Laporan Dishub');if(period.type==='all')folderId=await folder(drive,recapRoot,'Semua Laporan');else{const yearFolder=await folder(drive,recapRoot,String(period.year));folderId=period.type==='year'?yearFolder:await folder(drive,yearFolder,period.label)}const file=await drive.files.create({requestBody:{name:`Rekap ${period.label}`,mimeType:'application/vnd.google-apps.spreadsheet',parents:[folderId]},fields:'id,webViewLink'});fileId=file.data.id!;url=file.data.webViewLink||`https://docs.google.com/spreadsheets/d/${fileId}`;}
 const sheets=google.sheets({version:'v4',auth});await sheets.spreadsheets.values.clear({spreadsheetId:fileId,range:'Sheet1'});await sheets.spreadsheets.values.update({spreadsheetId:fileId,range:'Sheet1!A1',valueInputOption:'RAW',requestBody:{values}});await sheets.spreadsheets.batchUpdate({spreadsheetId:fileId,requestBody:{requests:[{unmergeCells:{range:{sheetId:0,startRowIndex:0,endRowIndex:3,startColumnIndex:0,endColumnIndex:22}}},{mergeCells:{range:{sheetId:0,startRowIndex:0,endRowIndex:1,startColumnIndex:0,endColumnIndex:22},mergeType:'MERGE_ALL'}},{mergeCells:{range:{sheetId:0,startRowIndex:1,endRowIndex:2,startColumnIndex:0,endColumnIndex:22},mergeType:'MERGE_ALL'}},{mergeCells:{range:{sheetId:0,startRowIndex:2,endRowIndex:3,startColumnIndex:0,endColumnIndex:22},mergeType:'MERGE_ALL'}},{repeatCell:{range:{sheetId:0,startRowIndex:0,endRowIndex:1,startColumnIndex:0,endColumnIndex:22},cell:{userEnteredFormat:{backgroundColor:rgb(30,58,138),horizontalAlignment:'CENTER',textFormat:{bold:true,foregroundColor:rgb(255,255,255),fontSize:15}}},fields:'userEnteredFormat'}},{repeatCell:{range:{sheetId:0,startRowIndex:1,endRowIndex:2,startColumnIndex:0,endColumnIndex:22},cell:{userEnteredFormat:{backgroundColor:rgb(14,116,144),horizontalAlignment:'CENTER',textFormat:{bold:true,foregroundColor:rgb(255,255,255)}}},fields:'userEnteredFormat'}},{repeatCell:{range:{sheetId:0,startRowIndex:3,endRowIndex:4,startColumnIndex:0,endColumnIndex:22},cell:{userEnteredFormat:{backgroundColor:rgb(15,23,42),wrapStrategy:'WRAP',textFormat:{bold:true,foregroundColor:rgb(255,255,255)}}},fields:'userEnteredFormat'}},{repeatCell:{range:{sheetId:0,startRowIndex:4,endRowIndex:Math.max(5,values.length),startColumnIndex:0,endColumnIndex:22},cell:{userEnteredFormat:{wrapStrategy:'WRAP',borders:{bottom:{style:'SOLID',color:rgb(226,232,240)}}}},fields:'userEnteredFormat.wrapStrategy,userEnteredFormat.borders'}},{updateSheetProperties:{properties:{sheetId:0,gridProperties:{frozenRowCount:4}},fields:'gridProperties.frozenRowCount'}},{autoResizeDimensions:{dimensions:{sheetId:0,dimension:'COLUMNS',startIndex:0,endIndex:22}}}]}});
 const {error:saveError}=await admin.from('google_combined_recap_sheets').upsert({user_id:user.id,recap_type:period.type,period_key:period.key,spreadsheet_id:fileId,spreadsheet_url:url,folder_id:folderId||null,updated_at:new Date().toISOString()});if(saveError)throw saveError;return NextResponse.redirect(new URL('/laporan/export-sukses?url='+encodeURIComponent(url),req.url));
}catch(e){return NextResponse.json({error:'Export rekap gagal: '+reason(e)},{status:500});}}
