import Link from 'next/link';
import {createClient} from '@/lib/supabase/server';

type Params={periode?:string;kecamatan?:string;jenis?:string;asal?:string};
type DashRow={id:string;nomor:string;waktu:string;pelapor:string;lokasi:string;kecamatan:string;kelurahan:string;jenis:string;tingkat:string;status:string;asal:'Manual'|'Import';href:string};
type History={reportId:string;status:string;createdAt:string;handledAt?:string|null;staff?:string|null;source:'Manual'|'Import'};
const statusColor=(v:string)=>v==='Selesai'?'bg-emerald-500':v==='Dalam Proses'?'bg-blue-500':'bg-amber-500';
const levelStyle=(v:string)=>v==='Darurat'?'bg-rose-600 text-white':v==='Berat'?'bg-rose-50 text-rose-700 ring-1 ring-rose-100':v==='Sedang'?'bg-amber-50 text-amber-700 ring-1 ring-amber-100':'bg-emerald-50 text-emerald-700 ring-1 ring-emerald-100';
const statusStyle=(v:string)=>v==='Selesai'?'bg-emerald-50 text-emerald-700':v==='Dalam Proses'?'bg-blue-50 text-blue-700':'bg-amber-50 text-amber-700';
const stamp=(v:string)=>new Date(v).toLocaleString('id-ID',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Jakarta'});
const dateKey=(v:Date|string)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v));

export default async function Dashboard({searchParams}:{searchParams:Params}){
  const period=['all','today','week','month','year'].includes(searchParams.periode||'')?searchParams.periode!:'month';
  const kecamatan=(searchParams.kecamatan||'').trim(),jenis=(searchParams.jenis||'').trim(),asal=['Manual','Import'].includes(searchParams.asal||'')?searchParams.asal!:'';
  const s=createClient(),now=new Date();let start:string|undefined;
  if(period==='today')start=new Date(now.getFullYear(),now.getMonth(),now.getDate()).toISOString();
  if(period==='week')start=new Date(now.getTime()-6*864e5).toISOString();
  if(period==='month')start=new Date(now.getFullYear(),now.getMonth(),1).toISOString();
  if(period==='year')start=new Date(now.getFullYear(),0,1).toISOString();

  let manual=s.from('laporan_kerusakan').select('id,nomor_laporan,created_at,waktu_laporan,nama_pelapor,nama_jalan,kecamatan,kelurahan,jenis_perlengkapan,tingkat_kerusakan,status').order('waktu_laporan',{ascending:false}).limit(1000);
  let imported=s.from('imported_laporan_kerusakan').select('id,nomor_import,waktu_laporan,nama_pelapor,nama_jalan,kecamatan,kelurahan,jenis_perlengkapan,tingkat_kerusakan,status').order('waktu_laporan',{ascending:false}).limit(1000);
  if(start){manual=manual.gte('waktu_laporan',start);imported=imported.gte('waktu_laporan',start)}
  if(kecamatan){manual=manual.eq('kecamatan',kecamatan);imported=imported.eq('kecamatan',kecamatan)}
  if(jenis){manual=manual.eq('jenis_perlengkapan',jenis);imported=imported.eq('jenis_perlengkapan',jenis)}
  const [{data:m},{data:i},{data:kecRefs},{data:typeRefs}]=await Promise.all([manual,imported,s.from('ref_kecamatan').select('nama').order('nama'),s.from('ref_jenis_perlengkapan').select('nama').order('nama')]);
  const rows:DashRow[]=[
    ...((asal!=='Import'?m:[])||[]).map(r=>({id:r.id,nomor:r.nomor_laporan,waktu:r.waktu_laporan||r.created_at,pelapor:r.nama_pelapor,lokasi:r.nama_jalan,kecamatan:r.kecamatan,kelurahan:r.kelurahan,jenis:r.jenis_perlengkapan,tingkat:r.tingkat_kerusakan,status:r.status,asal:'Manual' as const,href:'/laporan/'+r.id})),
    ...((asal!=='Manual'?i:[])||[]).map(r=>({id:r.id,nomor:r.nomor_import,waktu:r.waktu_laporan,pelapor:r.nama_pelapor,lokasi:r.nama_jalan,kecamatan:r.kecamatan,kelurahan:r.kelurahan,jenis:r.jenis_perlengkapan,tingkat:r.tingkat_kerusakan,status:r.status,asal:'Import' as const,href:'/laporan/import/arsip/'+r.id}))
  ].sort((a,b)=>new Date(b.waktu).getTime()-new Date(a.waktu).getTime());

  const manualIds=rows.filter(r=>r.asal==='Manual').slice(0,200).map(r=>r.id),importIds=rows.filter(r=>r.asal==='Import').slice(0,200).map(r=>r.id);
  const [{data:mh},{data:ih}]=await Promise.all([
    manualIds.length?s.from('laporan_penanganan').select('laporan_id,status,created_at,waktu_penanganan,petugas_menangani').in('laporan_id',manualIds).order('created_at',{ascending:false}).limit(250):Promise.resolve({data:[]}),
    importIds.length?s.from('imported_laporan_penanganan').select('laporan_import_id,status,created_at,waktu_penanganan,petugas_menangani').in('laporan_import_id',importIds).order('created_at',{ascending:false}).limit(250):Promise.resolve({data:[]})
  ]);
  const histories:History[]=[...(mh||[]).map(x=>({reportId:x.laporan_id,status:x.status,createdAt:x.created_at,handledAt:x.waktu_penanganan,staff:x.petugas_menangani,source:'Manual' as const})),...(ih||[]).map(x=>({reportId:x.laporan_import_id,status:x.status,createdAt:x.created_at,handledAt:x.waktu_penanganan,staff:x.petugas_menangani,source:'Import' as const}))].sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime());

  const waiting=rows.filter(r=>r.status==='Belum Ditangani').length,processing=rows.filter(r=>r.status==='Dalam Proses').length,done=rows.filter(r=>r.status==='Selesai').length,urgent=rows.filter(r=>r.tingkat==='Berat'||r.tingkat==='Darurat').length;
  const slaRows=rows.filter(r=>r.status!=='Selesai'&&Date.now()-new Date(r.waktu).getTime()>48*36e5),completion=rows.length?Math.round(done/rows.length*100):0;
  const reportMap=new Map(rows.map(r=>[r.id,r]));
  const completedByReport=new Map<string,number>();histories.filter(h=>h.status==='Selesai').forEach(h=>{const at=new Date(h.handledAt||h.createdAt).getTime(),old=completedByReport.get(h.reportId);if(!old||at<old)completedByReport.set(h.reportId,at)});
  const durations=[...completedByReport].map(([id,end])=>{const row=reportMap.get(id);return row?(end-new Date(row.waktu).getTime())/36e5:0}).filter(x=>x>=0&&Number.isFinite(x));
  const avgHours=durations.length?Math.round(durations.reduce((a,b)=>a+b,0)/durations.length):0;
  const priority=rows.filter(r=>r.status!=='Selesai').sort((a,b)=>{const rank=(x:DashRow)=>x.tingkat==='Darurat'?3:x.tingkat==='Berat'?2:Date.now()-new Date(x.waktu).getTime()>48*36e5?1:0;return rank(b)-rank(a)||new Date(a.waktu).getTime()-new Date(b.waktu).getTime()}).slice(0,5);
  const districts=Object.entries(rows.reduce<Record<string,number>>((a,r)=>{a[r.kecamatan]=(a[r.kecamatan]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]),maxDistrict=Math.max(...districts.map(x=>x[1]),1);
  const types=Object.entries(rows.reduce<Record<string,number>>((a,r)=>{a[r.jenis]=(a[r.jenis]||0)+1;return a},{})).sort((a,b)=>b[1]-a[1]).slice(0,6),maxType=Math.max(...types.map(x=>x[1]),1);
  const days=Array.from({length:7},(_,n)=>{const d=new Date(now.getTime()-(6-n)*864e5);return {key:dateKey(d),label:new Intl.DateTimeFormat('id-ID',{weekday:'short',day:'numeric',timeZone:'Asia/Jakarta'}).format(d)}});
  const trend=days.map(d=>({...d,incoming:rows.filter(r=>dateKey(r.waktu)===d.key).length,completed:histories.filter(h=>h.status==='Selesai'&&dateKey(h.handledAt||h.createdAt)===d.key).length})),maxTrend=Math.max(...trend.flatMap(x=>[x.incoming,x.completed]),1);
  const manualCount=rows.filter(r=>r.asal==='Manual').length,importCount=rows.length-manualCount;
  const activities=histories.slice(0,6).map(h=>({time:h.createdAt,title:`Status diperbarui menjadi ${h.status}`,detail:`${reportMap.get(h.reportId)?.nomor||'Laporan'}${h.staff?' · '+h.staff:''}`,href:reportMap.get(h.reportId)?.href||'/laporan/rekap',color:statusColor(h.status)}));
  const activeFilter=Boolean(kecamatan||jenis||asal||period!=='month');

  return <section className="space-y-5">
    <header className="overflow-hidden rounded-3xl bg-gradient-to-br from-indigo-950 via-indigo-800 to-cyan-700 p-6 text-white shadow-lg md:p-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><div className="flex items-center gap-2"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-300"/><p className="text-xs font-bold tracking-[.16em] text-cyan-200">PUSAT MONITORING OPERASIONAL</p></div><h1 className="mt-3 text-2xl font-bold md:text-3xl">Dashboard Perlengkapan Jalan</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-indigo-100">Pantau laporan masuk, prioritas lapangan, progres penanganan, dan pemerataan wilayah dalam satu layar.</p></div><div className="flex flex-wrap gap-2"><Link href="/laporan/rekap" className="rounded-xl bg-white/10 px-4 py-2.5 text-sm font-semibold ring-1 ring-white/20 transition hover:bg-white/20">Buka Rekap</Link><Link href="/laporan/tambah" className="rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-indigo-700 shadow-sm transition hover:-translate-y-0.5">+ Laporan Baru</Link></div></div></header>
    <form className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-2 xl:grid-cols-[1.1fr_1fr_1.2fr_1fr_auto]"><Select name="periode" label="Periode" value={period} options={[['today','Hari ini'],['week','7 hari terakhir'],['month','Bulan ini'],['year','Tahun ini'],['all','Semua waktu']]}/><Select name="asal" label="Sumber data" value={asal} options={[['','Manual + Import'],['Manual','Laporan manual'],['Import','Data import']]}/><Select name="kecamatan" label="Kecamatan" value={kecamatan} options={[['','Semua kecamatan'],...(kecRefs||[]).map(x=>[x.nama,x.nama])]}/><Select name="jenis" label="Jenis perlengkapan" value={jenis} options={[['','Semua jenis'],...(typeRefs||[]).map(x=>[x.nama,x.nama])]}/><div className="flex items-end gap-2"><button className="h-10 rounded-xl bg-indigo-700 px-5 text-sm font-semibold text-white hover:bg-indigo-800">Terapkan</button>{activeFilter&&<Link href="/dashboard" className="grid h-10 place-items-center rounded-xl border px-3 text-sm font-semibold text-slate-500 hover:bg-slate-50">Reset</Link>}</div></form>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6"><Kpi href="#ringkasan" label="Total Laporan" value={rows.length} note={`${manualCount} manual · ${importCount} import`} color="from-indigo-500 to-violet-600" icon="▤"/><Kpi href="#prioritas" label="Belum Ditangani" value={waiting} note="Memerlukan tindak lanjut" color="from-amber-400 to-orange-500" icon="!"/><Kpi href="#prioritas" label="Dalam Proses" value={processing} note="Sedang ditangani" color="from-blue-400 to-blue-600" icon="↻"/><Kpi href="#efektivitas" label="Selesai" value={done} note={`${completion}% dari laporan`} color="from-emerald-400 to-emerald-600" icon="✓"/><Kpi href="#prioritas" label="Prioritas Tinggi" value={urgent} note="Berat atau darurat" color="from-rose-400 to-rose-600" icon="▲"/><Kpi href="#prioritas" label="Lewat 48 Jam" value={slaRows.length} note="Belum selesai" color="from-fuchsia-500 to-purple-600" icon="◷"/></div>
    <div id="ringkasan" className="grid gap-5 xl:grid-cols-[minmax(0,1.8fr)_minmax(300px,1fr)]"><Panel title="Tren Operasional 7 Hari" subtitle="Perbandingan laporan masuk dan laporan selesai"><div className="mt-6 flex h-56 items-end gap-2 sm:gap-4">{trend.map(x=><div key={x.key} className="flex min-w-0 flex-1 flex-col items-center"><div className="mb-2 flex h-40 w-full items-end justify-center gap-1.5"><Bar value={x.incoming} max={maxTrend} color="bg-indigo-500"/><Bar value={x.completed} max={maxTrend} color="bg-emerald-400"/></div><p className="truncate text-[10px] text-slate-500 sm:text-xs">{x.label}</p></div>)}</div><div className="mt-4 flex justify-center gap-5 text-xs text-slate-500"><Legend color="bg-indigo-500" label="Laporan masuk"/><Legend color="bg-emerald-400" label="Selesai"/></div></Panel><Panel title="Komposisi Status" subtitle="Proporsi progres pada filter aktif"><div className="mt-6 flex flex-col items-center"><div className="relative grid h-40 w-40 place-items-center rounded-full" style={{background:rows.length?`conic-gradient(#10b981 0 ${completion}%, #3b82f6 ${completion}% ${completion+Math.round(processing/rows.length*100)}%, #f59e0b 0)`:'#e2e8f0'}}><div className="grid h-28 w-28 place-items-center rounded-full bg-white text-center shadow-inner"><div><b className="text-2xl text-slate-900">{completion}%</b><p className="text-[10px] text-slate-400">terselesaikan</p></div></div></div><div className="mt-6 grid w-full grid-cols-3 gap-2 text-center"><MiniStatus color="bg-amber-500" value={waiting} label="Belum"/><MiniStatus color="bg-blue-500" value={processing} label="Proses"/><MiniStatus color="bg-emerald-500" value={done} label="Selesai"/></div></div></Panel></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.65fr)_minmax(300px,1fr)]"><Panel id="prioritas" title="Perlu Segera Ditangani" subtitle="Diurutkan dari kondisi darurat, berat, lalu laporan tertua" action={<Link href="/laporan/rekap" className="text-xs font-semibold text-indigo-700">Lihat seluruh laporan →</Link>}><div className="mt-4 divide-y divide-slate-100">{priority.map(r=>{const age=Math.max(0,Math.floor((Date.now()-new Date(r.waktu).getTime())/36e5));return <article key={r.asal+r.id} className="grid gap-3 py-4 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={'rounded-full px-2.5 py-1 text-[10px] font-bold '+levelStyle(r.tingkat)}>{r.tingkat}</span><span className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{r.asal}</span><span className="text-xs text-slate-400">{age<24?age+' jam':Math.floor(age/24)+' hari'} menunggu</span></div><Link href={r.href} className="mt-2 block truncate font-bold text-slate-800 hover:text-indigo-700">{r.nomor}</Link><p className="mt-1 truncate text-sm text-slate-500">{r.lokasi} · {r.kelurahan}, {r.kecamatan}</p></div><div className="flex items-center gap-2"><span className={'rounded-lg px-2.5 py-1.5 text-xs font-semibold '+statusStyle(r.status)}>{r.status}</span><Link href={r.href} className="rounded-lg bg-indigo-700 px-3 py-2 text-xs font-semibold text-white">Kelola</Link></div></article>})}{!priority.length&&<Empty text="Tidak ada laporan yang memerlukan penanganan."/>}</div></Panel><Panel title="Sebaran Kecamatan" subtitle="Jumlah laporan berdasarkan lokasi kejadian"><div className="mt-6 space-y-5">{districts.map(([name,count])=><Progress key={name} label={name} value={count} max={maxDistrict} color="from-cyan-400 to-indigo-500"/>)}{!districts.length&&<Empty text="Belum ada data wilayah."/>}</div></Panel></div>
    <div id="efektivitas" className="grid gap-5 xl:grid-cols-3"><Panel title="Efektivitas Penanganan" subtitle="Indikator hasil pada periode terpilih"><div className="mt-5 grid grid-cols-2 gap-3"><Metric value={`${completion}%`} label="Tingkat selesai"/><Metric value={avgHours?avgHours<24?`${avgHours} jam`:`${Math.round(avgHours/24)} hari`:'–'} label="Rata-rata penanganan"/><Metric value={String(slaRows.length)} label="Melewati 48 jam"/><Metric value={String(durations.length)} label="Riwayat terukur"/></div><p className="mt-4 rounded-xl bg-slate-50 px-3 py-2 text-[11px] leading-5 text-slate-500">Durasi dihitung dari waktu laporan sampai riwayat pertama berstatus selesai.</p></Panel><Panel title="Jenis Perlengkapan Dominan" subtitle="Fokus kerusakan yang paling sering dilaporkan"><div className="mt-5 space-y-4">{types.map(([name,count])=><Progress key={name} label={name} value={count} max={maxType} color="from-indigo-500 to-violet-500"/>)}{!types.length&&<Empty text="Belum ada data jenis."/>}</div></Panel><Panel title="Aktivitas Penanganan" subtitle="Pembaruan status terbaru oleh petugas"><div className="mt-5 space-y-0">{activities.map((a,n)=><Link href={a.href} key={a.time+n} className="group flex gap-3"><div className="flex flex-col items-center"><span className={'mt-1.5 h-2.5 w-2.5 rounded-full ring-4 ring-white '+a.color}/>{n<activities.length-1&&<span className="h-full w-px bg-slate-200"/>}</div><div className="min-w-0 pb-5"><p className="text-sm font-semibold text-slate-700 group-hover:text-indigo-700">{a.title}</p><p className="mt-0.5 truncate text-xs text-slate-500">{a.detail}</p><p className="mt-1 text-[10px] text-slate-400">{stamp(a.time)}</p></div></Link>)}{!activities.length&&<Empty text="Belum ada aktivitas penanganan."/>}</div></Panel></div>
  </section>
}

function Select({name,label,value,options}:{name:string;label:string;value:string;options:string[][]}){return <label className="text-xs font-semibold text-slate-600">{label}<select name={name} defaultValue={value} className="mt-1.5 h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-normal text-slate-700 outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-50">{options.map(([v,l])=><option value={v} key={v||'all'}>{l}</option>)}</select></label>}
function Kpi({href,label,value,note,color,icon}:{href:string;label:string;value:number;note:string;color:string;icon:string}){return <a href={href} className="surface-hover group rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-3xl font-bold tracking-tight text-slate-900">{value}</p></div><span className={'grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br text-sm font-bold text-white shadow-sm '+color}>{icon}</span></div><p className="mt-3 truncate text-[11px] text-slate-400">{note}</p></a>}
function Panel({title,subtitle,action,id,children}:{title:string;subtitle:string;action?:React.ReactNode;id?:string;children:React.ReactNode}){return <section id={id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-slate-900">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{subtitle}</p></div>{action}</div>{children}</section>}
function Bar({value,max,color}:{value:number;max:number;color:string}){return <div title={String(value)} className={'relative min-h-1 w-3 rounded-t-md transition-all sm:w-5 '+color} style={{height:`${Math.max(value?8:2,value/max*100)}%`}}><span className="absolute -top-5 left-1/2 -translate-x-1/2 text-[9px] font-bold text-slate-500">{value||''}</span></div>}
function Legend({color,label}:{color:string;label:string}){return <span className="flex items-center gap-2"><i className={'h-2.5 w-2.5 rounded-sm '+color}/>{label}</span>}
function MiniStatus({color,value,label}:{color:string;value:number;label:string}){return <div className="rounded-xl bg-slate-50 p-2"><span className={'mx-auto block h-1 w-6 rounded '+color}/><b className="mt-1 block text-sm">{value}</b><span className="text-[10px] text-slate-400">{label}</span></div>}
function Progress({label,value,max,color}:{label:string;value:number;max:number;color:string}){return <div><div className="mb-1.5 flex justify-between gap-3 text-xs"><span className="truncate text-slate-600">{label}</span><b className="text-slate-800">{value}</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={'h-full rounded-full bg-gradient-to-r '+color} style={{width:`${value/max*100}%`}}/></div></div>}
function Metric({value,label}:{value:string;label:string}){return <div className="rounded-xl border border-slate-100 bg-slate-50/70 p-3"><b className="text-xl text-slate-900">{value}</b><p className="mt-1 text-[10px] font-medium text-slate-500">{label}</p></div>}
function Empty({text}:{text:string}){return <p className="py-8 text-center text-sm text-slate-400">{text}</p>}
